// GAMES NETWORK REQUEST TYPES
export const FETCH_GAMES_STARTED = "FETCH_GAMES_STARTED";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_ERROR = "FETCH_GAMES_ERROR";
export const FETCH_CACHED_GAMES = "FETCH_CACHED_GAMES";

// GAME ACTION
export const ADD_FAVORITE_GAME = "ADD_FAVORITE_GAME";
export const REMOVE_FAVORITE_GAME = "REMOVE_FAVORITE_GAME";
